### ISSUE TITLE
Unicode primes

### ISSUE THREAD

**Issue by stevengj** [bartp5/libtexprintf#21]
`t'` and `t''` get rendered as-is using ASCII quotes, but they could be rendered using Unicode prime characters `t′` and `t″`.

[Here](https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/latex_symbols.jl#L107-L111) are several Unicode primes.

**Comment by bartp5** [comment]
currently libtexprintf has the `\prime` `\second` `\third` and `\fourth` commands to get those symbols. Obviously it is nice to automatically parse this and it seems simple enough. I'll have a look.

**Comment by stevengj** [comment]
Great!  I would suggest a different fallback, though for more than 4 primes, though.  Right now you have `src/utftex "y'''''" ` render as
```
y⁗′
```
Maybe it should render as `y′′′′′` instead?  i.e. fallback to repeating `′`?
