### ISSUE TITLE
manpage not up to date

### ISSUE THREAD

**Issue by cabo** [bartp5/libtexprintf#23]
```
$ utftex "a_{utc} < a_{ntp}"
a    < aₙₜₚ
 utc
```

In github, you may not be able to see the subscript characters that utftex uses for the "ntp" suffix.
(Maybe just copy/paste it to something else, e.g., pbpaste in terminal.)

Even worse than the interoperability problems here is the uneven handling of "utc" and "ntp" -- of course, I know why this happens, but I'd rather have a way to completely switch off the feature that uses subscript characters.

**Comment by bartp5** [comment]
Yes I know, I already implemented this option. However, it seems I forgot to update the man page (sorry about that). The option is '-m'. Try:
```
utftex -m "a_{utc} < a_{ntp}"
a    < a
 utc    ntp
```

**Comment by cabo** [comment]
Thank you!
What works for me.
I now hardwired this option into kramdown-rfc (https://rfc.space).
What is the minimum utftex version I need to have for `-m`?

**Comment by bartp5** [comment]
I directly implemented it when I implemented together with the sub/superscript characters, that was version 1.21.

Somewhat off-topic but for your use case I would suggest to add the option -e (since version 1.22). Due to the command line option parsing, utftex has a problem with equations starting with a minus. To avoid utftex trying to parse an equation as an option, you can pass -e to end the option parser, e.g. without -e
```
utftex -m '-x=\int_a^b ...'
utftex: invalid option -- 'x'
```
and with -e
```
utftex -m -e '-x=\int_a^b ...'
    b
   ⌠
-x=⎮  ...
   ⌡
    a
```

**Comment by cabo** [comment]
Thank you for the hint.  I noticed that I can pipe the formula to stdin as well?  I like that somewhat better than shell-escaping it.

**Comment by cabo** [comment]
Oh, and while I have your attention:

```
enum_{acc} \approx 48 + \lfloor 2 \cdot log_{10} {acc \over \mathrm{s}} - \epsilon \rfloor
```

renders

```
                           acc
   enum    ≈48 + ⌊2 ⋅log   ──── - ϵ⌋
       acc              10  s
```

which is great except that ≈48 runs together.  How do elicit some space?

**Comment by cabo** [comment]
And one more: do you have a "--no-m" equivalent, so a user can undo my presetting of -m?

**Comment by bartp5** [comment]
> Oh, and while I have your attention:
> 
> ```
> enum_{acc} \approx 48 + \lfloor 2 \cdot log_{10} {acc \over \mathrm{s}} - \epsilon \rfloor
> ```
> 
> renders
> 
> ```
>                            acc
>    enum    ≈48 + ⌊2 ⋅log   ──── - ϵ⌋
>        acc              10  s
> ```
> 
> which is great except that ≈48 runs together. How do elicit some space?

the `\approx` command "swallows" the following space. If you add two spaces after the  `\approx` you get  
```
utftex 'enum_{acc} \approx  48 + \left\lfloor 2 \cdot log_{
10} {acc \over \mathrm{s}} - \epsilon \right\rfloor'
               ⎢         acc     ⎥
enum    ≈ 48 + ⎢2 ⋅log₁₀ ──── - ϵ⎥
    acc        ⎣          s      ⎦
```
If you add more spaces they will be ignored. If you need more spacing you can escape spaces too. 
The rationale is that it should be possible to not have a space after a command but I need at least one space to recognize the end of the command.

**Comment by bartp5** [comment]
Updated manpage.
