### ISSUE TITLE
Gui for utftex

### ISSUE THREAD

**Issue by wpeaton** [bartp5/libtexprintf#25]
I made a GUI using PyQt6. It should be easily translatable to PySide6. It borrows a lot of ideas from AsciiTeX.

It's designed to be made into an executable file with PyInstaller.

[utftexgui.zip](https://github.com/bartp5/libtexprintf/files/14213469/utftexgui.zip)

**Comment by bartp5** [comment]
Hi,
A nice project. I suggest making a github (or other platform of your preference)  repository for it, and I would be happy to add a link here to your project. 
I did a small test of your code, and it works fine. I had to change a few things as you assume a windows executable in the same directory as your program (I am on linux and utftex is in my path). Not sure why, but after trying to build an executable with pyinstaller I had to copy the file utftexgui.ui to the dist/utftex_gui directory.

**Comment by wpeaton** [comment]
I made a new repository on GitHub. [https://github.com/wpeaton/utftex-gui/](https://github.com/wpeaton/utftex-gui/).

For pyinstaller it's a little extra work, but if you create a [SPEC](https://pyinstaller.org/en/stable/spec-files.html) file, you can list all of the extra files you want to include (like .ui files, icons, README, etc.). To use the spec file during "compile" use command `pyinstaller <options> myfile.spec` instead of `pyinstaller <options> myfile.py`

**Comment by bartp5** [comment]
Thanks for making a repository.  I added a section in the README linking to several projects using libtexprintf/utftex.
